### ISSUE TITLE
Is this plugin compatibile with Oracle XE?

### ISSUE THREAD

**Issue by gisprogrammer** [mirmas/SaveFilesToDisk#1]
Is this plugin compatible with Oracle XE?
Oracle XE does not support Java. Is this plugin using Java?
Yes, this plugin is compatible with Oracle XE. No Java is needed.

**Comment by mirmas** [comment]
Yes, this plugin is compatible with Oracle XE. No Java is needed.

**Comment by mirmas** [comment]
Yes, this plugin is compatible with Oracle XE. No Java is needed.
